name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: MariamRashad6  # Replace with your GitHub username
          outputs: "github-contribution-grid-snake.svg"

      # Push the snake to the output branch
      - name: Commit and Push
        run: |
          git config --global user.name "Mariam Rashad"
          git config --global user.email "mariamrashad062@gmail.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Generated Snake Animation"
          git push
