name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (adjust as needed)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: MariamRashad6  # Change to your GitHub username

      - name: Commit and Push the Snake Animation
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add -A
          git commit -m "Generated GitHub Snake Animation"
          git push
